"""Add created_at column to Domain model

Revision ID: f1cf49244d61
Revises: 440228a4c856
Create Date: 2024-11-12 04:55:18.979579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1cf49244d61'
down_revision = '440228a4c856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('domain', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('domain', 'create_at')
    
    # ### end Alembic commands ###
